[tool.poetry]
name = "rest_api"
version = "0.1.0"
description = "description"
authors = ["Maksym <wery5859@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
fastapi = "^0.70.0"
sqlalchemy = "^1.4.0"
psycopg2 = "^2.9.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"