# Generated by Django 5.0.4 on 2024-04-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_alter_quote_author_fullname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'managed': False},
        ),
    ]
