# Generated by Django 5.0.4 on 2024-04-06 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0005_alter_author_table_alter_quote_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
        migrations.AlterModelTable(
            name='quote',
            table='quotes',
        ),
    ]
