# Generated by Django 5.0.4 on 2024-04-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_alter_author_table_alter_quote_table'),
    ]

    operations = [
    ]
